### ISSUE TITLE
Cannot compile with apache-maven-2.1.0 on Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tst2005googlecode/step2#17]
```
What steps will reproduce the problem?
1. svn checkout http://step2.googlecode.com/svn/code/java/trunk/ step2
2. cd step2
3. mvn install

What is the expected output? What do you see instead?

Successful compile but. 

[INFO] Copying 0 resource
[WARNING] POM for
'org.openid4java:openid4java-consumer:pom:0.9.5-SNAPSHOT:compi
le' is invalid.

Its dependencies (if any) will NOT be available to the current build.
[WARNING] POM for
'org.openid4java:openid4java-server:pom:0.9.5-SNAPSHOT:compile
' is invalid.
...
...
could not parse error message:
org\openid4java\discovery\xri\LocalXriResolver.ja
va(org\openid4java\discovery\xri:LocalXriResolver.java):204: cannot find symbol
symbol  : class XRI
location: class org.openid4java.discovery.xri.LocalXriResolver
                new XRI(identifier.toString()),
                    ^


[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Sun Apr 26 22:54:50 EEST 2009
[INFO] Final Memory: 19M/34M
[INFO] ------------------------------------------------------------------------


What version of the product are you using? On what operating system?

apache maven 2.1.0 , jdk 1.6.0_10-rc2

Please provide any additional information below.


```

Original issue reported on code.google.com by `esur.harun@gmail.com` on 26 Apr 2009 at 7:55
